#!/bin/sh
set -e

PKG="bam-util"
VER="1.0.11"
PKG_DIR=/usr/lib/${PKG}${VER}

if [ "$1" = "configure" ]; then
    for pathname in ${PKG_DIR}/bin/*; do
        filename=`basename $pathname`
        update-alternatives --install /usr/bin/${filename} ${filename} /usr/bin/${filename}${VER} 1
    done
fi
